# Generated by Django 5.2.8 on 2025-11-25 17:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.CharField(blank=True, max_length=10, null=True)),
                ('aktivite_turu', models.CharField(choices=[('rating', 'Puanlama'), ('review', 'Yorum'), ('library', 'Kütüphane İşlemi'), ('follow', 'Takip Etme'), ('list_add', 'Özel Listeye Ekleme')], max_length=20)),
                ('meta', models.JSONField(default=dict)),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OzelListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=10)),
                ('yorum', models.TextField()),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kutuphane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=10)),
                ('durum', models.CharField(choices=[('izledim', 'İzledim'), ('izlenecek', 'İzlenecek'), ('okudum', 'Okudum'), ('okunacak', 'Okunacak')], max_length=20)),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'content_id', 'durum')},
            },
        ),
        migrations.CreateModel(
            name='OzelListeIcerik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=10)),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icerikler', to='api.ozelliste')),
            ],
            options={
                'unique_together': {('liste', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='Puan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=10)),
                ('puan', models.IntegerField()),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='Takip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('takip_eden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('takip_edilen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('takip_eden', 'takip_edilen')},
            },
        ),
    ]
