# Generated by Django 5.2.8 on 2025-11-28 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kutuphane',
            unique_together={('kullanici', 'content_id')},
        ),
    ]
