# Generated by Django 5.2.8 on 2025-11-29 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_kutuphane_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AktiviteYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.TextField()),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('aktivite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='api.aktivite')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AktiviteLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('aktivite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.aktivite')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('aktivite', 'kullanici')},
            },
        ),
    ]
