# Generated by Django 5.2.8 on 2025-12-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aktiviteyorum_aktivitelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorum',
            name='tarih',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
